version: "3.8"

services:

  # MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

  # AwsMock
  awsmock:
    container_name: awsmock
    image: jensvogt/aws-mock:latest
    hostname: awsmock
    networks:
      - "local"
    ports:
      - "4566:4566"
      - "4567:4567"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [ "CMD", "awsmock", "s3",  "ls" ]
      interval: 60s
      timeout: 10s
      retries: 15

# Volumes
volumes:
  dbdata:

# Networks
networks:
  local:
    driver: "bridge"
