name: AWSMockBuild
on:
  release:
    types: [ created ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build Docker
        run: |
          VERSION=$(git sv cv)
          cd docker 
          docker build --no-cache --build-arg GH_TOKEN=${GH_TOKEN} -t aws-mock:$VERSION .

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag images
        run: |
          VERSION=$(git sv cv)
          docker tag aws-mock:$VERSION ${{ secrets.DOCKER_USER }}/aws-mock:$VERSION
          docker push ${{ secrets.DOCKER_USER }}/aws-mock:$VERSION
          docker tag aws-mock:$VERSION ${{ secrets.DOCKER_USER }}/aws-mock:latest
          docker push ${{ secrets.DOCKER_USER }}/aws-mock:latest
