name: AWSMockBuild
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build project
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ./build --config Release

      - name: Run tests
        run: cd build && ctest -V

      - name: Create docs
        run: cd build && make docs

  tag:
    name: Tag
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set GitHub Actions as commit author
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create tag
        id: create-tag
        run: |
          git sv tag
          VERSION=$(git sv cv)
          echo "::set-output name=tag::v$VERSION"
    outputs:
      tag: ${{ steps.create-tag.outputs.tag }}

  release:
    name: Release
    runs-on: self-hosted
    needs: [ tag ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create release notes
        run: |
          VERSION=$(git sv cv)
          git sv rn -t "$VERSION" > release-notes.md

      - name: Build Docker
        run: |
          VERSION=$(git sv cv)
          cd docker 
          docker build --no-cache -t aws-mock:$VERSION .

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    needs: [ release ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag images
        run: |
          VERSION=$(git sv cv)
          docker tag aws-mock:$VERSION ${{ secrets.DOCKER_USER }}/awsmock:latest
          docker push ${{ secrets.DOCKER_USER }}/aws-mock:latest

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#        with:
#          images: jensvogt/aws-mock
#          tags: |
#            type=ref,event=branch
#            type=ref,event=pr
#            type=semver,pattern={{version}}
#            type=semver,pattern={{major}}.{{minor}}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
#        with:
#          context: docker
#          file: ./docker/Dockerfile
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}