name: AWSMockBuild
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build project
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build ./build --config Release
      - name: Run tests
        run: cd build && ctest -V
      - name: Create docs
        run: cd build && make docs
      - name: Save artifacts
        run: |
          cd bin 
          mkdir downloads
          cp ../build/core/libawsmockcore.so ../build/db/libawsmockdb.so ../build/service/libawsmocksrv.so ../build/worker/libawsmockwrk.so ./downloads
          cp ../build/awsmock/aws-mock ../etc/aws-mock.properties ./downloads
          cd ../
          steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build project
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build ./build --config Release
      - name: Run tests
        run: cd build && ctest -V
      - name: Create docs
        run: cd build && make docs
      - name: Save artifacts
        run: |
          cd bin 
          mkdir downloads
          cp ../build/core/libawsmockcore.so ../build/db/libawsmockdb.so ../build/service/libawsmocksrv.so ../build/worker/libawsmockwrk.so ./downloads
          cp ../build/awsmock/awsmock ../etc/aws-mock.properties ./downloads
          cd ../
      - name: Semantic release
        run: |
            curl -L -O -J https://gitlab.com/mccleanp/semantic-release-bash/-/jobs/artifacts/<version>/raw/semantic-release?job=publish
            chmod +x semantic-release
            semantic-release

