name: AWSMockBuild
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build project
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ./build --config Release

      - name: Run tests
        run: cd build && ctest -V

      - name: Create docs
        run: cd build && make docs

  tag:
    name: Tag
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set GitHub Actions as commit author
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create tag
        id: create-tag
        run: |
          git sv tag
          VERSION=$(git sv cv)
          echo "::set-output name=tag::v$VERSION"
    outputs:
      tag: ${{ steps.create-tag.outputs.tag }}

  release:
    name: Release
    runs-on: self-hosted
    needs: [ tag ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create release notes
        run: |
          VERSION=$(git sv cv)
          git sv rn -t "$VERSION" > release-notes.md

      - name: Build Docker
        run: |
          VERSION=$(git sv cv)
          cd docker 
          docker build -t aws-mock:$VERSION .
