name: AWSMockBuild
on:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build project
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ./build --config Release

#      - name: Run tests
#        run: cd build && ctest -V

      - name: Create docs
        run: cd build && make docs

#  tag:
#    name: Tag
#    runs-on: self-hosted
#    needs: [ build ]
#    steps:
#      - name: Create tag artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: ${{github.ref_name}}
#          path: Release
#    outputs:
#      tag: ${{ steps.create-tag.outputs.tag }}

  release:
    name: Release
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker
        run: |
          VERSION=${{github.ref_name}}
          cd docker 
          docker build --no-cache -t aws-mock:$VERSION .

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    needs: [ release ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag images
        run: |
          VERSION=${{github.ref_name}}
          docker tag aws-mock:$VERSION ${{ secrets.DOCKER_USER }}/aws-mock:$VERSION
          docker push ${{ secrets.DOCKER_USER }}/aws-mock:$VERSION
          docker tag aws-mock:$VERSION ${{ secrets.DOCKER_USER }}/aws-mock:latest
          docker push ${{ secrets.DOCKER_USER }}/aws-mock:latest
