name: AWS Mock Release

on:
  workflow_run:
    workflows: [AWSMockBuild]
    types:
      - completed

jobs:
  release:
    if: ${{ github.ref_name == 'main' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup package.json
        run: echo '{"name":"aws-mock", "devDependencies":{"@semantic-release/git":"^10.0.1","@semantic-release/exec":"^6.0.3","semantic-release":"^19.0.5"}}' > package.json

      - name: Install dependencies
        run: npm install

      - name: Release
        run: npx semantic-release