name: AWS Mock
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build project
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build ./build --config Release
      - name: Run tests
        run: cd build && ctest -V
      - name: Create docs
        run: cd build && make docs
      - name: Create Artifact
        run: |
          mkdir release
          cp build/src/aws-mock release
          cp -R docs release
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: aws-mock-release
          path: release